# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  before_all do 
    setup_circle_ci
  end
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit alpha"
  lane :alpha do
    gradle(task: "clean assembleRelease")
  

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Promote aplha build to beta"
  lane :deploy do
    upload_to_play_store(track: 'alpha', track_promote_to: 'beta')
  end
end
